### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#264]
Also in Basics
```
gravity-force-lab : build : phet
Failure to grunt snapshot-1586132499377/gravity-force-lab:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab, brands: phet)
Building brand: phet
>> Webpack build complete: 4641ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for inverse-square-law-common a11y.tiny
  at locales.forEach.locale (/data/share/phet/continuous-testing/snapshot-1586132499377/chipper/js/grunt/getStringMap.js:213:9)
  at Array.forEach (<anonymous>:null:null)
  at partialStringKeys.forEach.partialStringKey (/data/share/phet/continuous-testing/snapshot-1586132499377/chipper/js/grunt/getStringMap.js:202:15)
  at Array.forEach (<anonymous>:null:null)
  at reposWithUsedStrings.forEach.repo (/data/share/phet/continuous-testing/snapshot-1586132499377/chipper/js/grunt/getStringMap.js:201:23)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1586132499377/chipper/js/grunt/getStringMap.js:153:24)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1586132499377/chipper/js/grunt/buildRunnable.js:109:21)

Full Error details:
{
  "generatedMessage": false,
  "name": "AssertionError [ERR_ASSERTION]",
  "code": "ERR_ASSERTION",
  "actual": false,
  "expected": true,
  "operator": "=="
}


Approximately 4/5/2020, 6:21:39 PM
gravity-force-lab : build : phet-io
Failure to grunt snapshot-1586132499377-phet-io/gravity-force-lab:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4440ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for inverse-square-law-common a11y.tiny
  at locales.forEach.locale (/data/share/phet/continuous-testing/snapshot-1586132499377-phet-io/chipper/js/grunt/getStringMap.js:213:9)
  at Array.forEach (<anonymous>:null:null)
  at partialStringKeys.forEach.partialStringKey (/data/share/phet/continuous-testing/snapshot-1586132499377-phet-io/chipper/js/grunt/getStringMap.js:202:15)
  at Array.forEach (<anonymous>:null:null)
  at reposWithUsedStrings.forEach.repo (/data/share/phet/continuous-testing/snapshot-1586132499377-phet-io/chipper/js/grunt/getStringMap.js:201:23)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1586132499377-phet-io/chipper/js/grunt/getStringMap.js:153:24)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1586132499377-phet-io/chipper/js/grunt/buildRunnable.js:109:21)

Full Error details:
{
  "generatedMessage": false,
  "name": "AssertionError [ERR_ASSERTION]",
  "code": "ERR_ASSERTION",
  "actual": false,
  "expected": true,
  "operator": "=="
}


Approximately 4/5/2020, 6:21:39 PM
gravity-force-lab : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586132499377/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 4/5/2020, 6:21:39 PM
gravity-force-lab : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586132499377/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab
9 out of 9 tests passed. 0 failed.

Approximately 4/5/2020, 6:21:39 PM
```

**Comment by zepumph** [comment]
This has been fixed. Closing
