### ISSUE TITLE
CT cannot read property get of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#267]
Also in Basics
```
gravity-force-lab : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at i.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:2381749)
at i.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1191067)
at i.handleKeyUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1190220)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:601837)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:602036)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:601578)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:596880)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:593666
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:394081)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591187429687%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:594072)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM

----------------------------------

gravity-force-lab : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at i.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:2381749)
at i.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1191067)
at i.handleKeyUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:1190220)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:601837)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:602036)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:601578)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:596880)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:593666
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:394081)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/build/phet/gravity-force-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591192858879%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:912:594072)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM

----------------------------------

gravity-force-lab : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591182355866%22%2C%22timestamp%22%3A1591186732271%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
at MassNode.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/inverse-square-law-common/js/view/ISLCObjectNode.js:355:47)
at MassNode.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:673:14)
at MassNode.handleBlur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/sun/js/accessibility/AccessibleValueHandler.js:654:16)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1851:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1883:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1809:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:1037:12)
at Input.focusoutAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:592:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591182355866/scenery/js/input/Input.js:740:30)
id: Bayes Chrome
Snapshot from 6/3/2020, 5:05:55 AM
```

**Comment by zepumph** [comment]
@jessegreenberg has been in these repos, let me know if I can do anything to help!

**Comment by jessegreenberg** [comment]
Sorry and thanks! Looks to be resolved now.
![image](https://user-images.githubusercontent.com/6396244/83689093-772b9100-a5bc-11ea-8f70-04bb640fa66b.png)
