### ISSUE TITLE
CT value failed isValidValue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#279]
Also in basics:
```
gravity-force-lab : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614720201618%22%2C%22timestamp%22%3A1614721700876%7D&brand=phet&ea&fuzz&supportsDescription&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescription&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 1.8
Error: Assertion failed: value failed isValidValue: 1.8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:122:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:191:14)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:103:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:129:7
id: Bayes Chrome
Snapshot from 3/2/2021, 2:23:21 PM

----------------------------------

gravity-force-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614720201618%22%2C%22timestamp%22%3A1614721667650%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: -3
Error: Assertion failed: value failed isValidValue: -3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:138:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:294:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:191:14)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:357:10)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:182:11)
id: Bayes Chrome
Snapshot from 3/2/2021, 2:23:21 PM

----------------------------------

gravity-force-lab : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614720201618%22%2C%22timestamp%22%3A1614722594890%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: -2
Error: Assertion failed: value failed isValidValue: -2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:122:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:191:14)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:103:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:120:7
id: Bayes Chrome
Snapshot from 3/2/2021, 2:23:21 PM

----------------------------------

gravity-force-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/phet-io-wrappers/state/?sim=gravity-force-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614720201618%22%2C%22timestamp%22%3A1614721659155%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: 0.9
Error: Assertion failed: value failed isValidValue: 0.9
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:122:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:191:14)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:103:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:120:7
id: Bayes Chrome
Snapshot from 3/2/2021, 2:23:21 PM

----------------------------------

gravity-force-lab : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/studio/?sim=gravity-force-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614720201618%22%2C%22timestamp%22%3A1614722656317%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: -3
Error: Assertion failed: value failed isValidValue: -3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/NumberProperty.js:122:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/axon/js/Property.js:191:14)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:103:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614720201618/inverse-square-law-common/js/model/ISLCModel.js:120:7
id: Bayes Chrome
Snapshot from 3/2/2021, 2:23:21 PM
```

**Comment by zepumph** [comment]
This will be covered by https://github.com/phetsims/inverse-square-law-common/issues/83

**Comment by zepumph** [comment]
Fixed by https://github.com/phetsims/inverse-square-law-common/commit/5115d720fec482959037568f454a4ace745590c9
