### ISSUE TITLE
CT linearFunction is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#281]
```
gravity-force-lab : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637683103029%22%2C%22timestamp%22%3A1637684696521%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: linearFunction is not a function
TypeError: linearFunction is not a function
at ISLCForceArrowNode.getLinearMappingToArrowWidth (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCForceArrowNode.js:96:20)
at ISLCForceArrowNode.redrawArrow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCForceArrowNode.js:139:38)
at MassNode.redrawForce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:323:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:235:18
at NumberProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/axon/js/Property.js:284:9)
at new ISLCObjectNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:230:33)
at new MassNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/view/MassNode.js:55:9)
at new GravityForceLabScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/view/GravityForceLabScreenView.js:79:27)
at Screen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/gravity-force-lab-main.js:36:112)
at Screen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Screen.js:206:27)
id: Bayes Chrome
Snapshot from 11/23/2021, 8:58:23 AM

----------------------------------

gravity-force-lab : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/phet-io-wrappers/input-record-and-playback/?sim=gravity-force-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637683103029%22%2C%22timestamp%22%3A1637684905099%7D
Uncaught Error: Uncaught TypeError: linearFunction is not a function
TypeError: linearFunction is not a function
at ISLCForceArrowNode.getLinearMappingToArrowWidth (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCForceArrowNode.js:96:20)
at ISLCForceArrowNode.redrawArrow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCForceArrowNode.js:139:38)
at MassNode.redrawForce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:323:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:235:18
at NumberProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/axon/js/Property.js:284:9)
at new ISLCObjectNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/inverse-square-law-common/js/view/ISLCObjectNode.js:230:33)
at new MassNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/view/MassNode.js:55:9)
at new GravityForceLabScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/view/GravityForceLabScreenView.js:79:27)
at Screen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/gravity-force-lab/js/gravity-force-lab-main.js:36:112)
at Screen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Screen.js:206:27)
id: Bayes Chrome
Snapshot from 11/23/2021, 8:58:23 AM
```

**Comment by zepumph** [comment]
Looks like this cleared up also. Like https://github.com/phetsims/gravity-and-orbits/issues/413
