### ISSUE TITLE
CT designed api changes detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#283]
```
gravity-force-lab : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643962261433%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/phet-io/js/phetioEngine.js:336:23)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM
```

**Comment by zepumph** [comment]
Fixed by https://github.com/phetsims/phet-io/commit/2f55312540f657d5c893a0dc6d163d50907d4e8c#diff-32eb810879d5cf8fc29cbccd53bc20fa8713eea8ef401dd531554850b93b5f6cR179, as are all the other examples of this failure.
