### ISSUE TITLE
CT canAnnounceProperties required

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#285]
```
gravity-force-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650368853818%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:241:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650368269659%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:241:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650370638094%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:241:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650369889238%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:241:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650367977696%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:219:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650368707039%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:241:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM

----------------------------------

gravity-force-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/gravity-force-lab/gravity-force-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1650366060350%22%2C%22timestamp%22%3A1650372304838%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
Error: Assertion failed: canAnnounceProperties required, this Utterance might not be connected to Node in the scene graph.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650366060350/assert/js/assert.js:25:13)
at assert (Voicing.ts:697:12)
at alertUtterance (GravityForceLabAlertManager.js:254:12)
at alertConstantSizeChangedPosition (GravityForceLabAlertManager.js:108:13)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (ISLCModel.js:219:67)
at step (Sim.ts:440:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:994:30)
id: Bayes Chrome
Snapshot from 4/19/2022, 5:01:00 AM
```

**Comment by zepumph** [comment]
Thanks! I think it would be good for @jessegreenberg to see this guy too.

**Comment by jessegreenberg** [comment]
Thanks, fixed in the above commit. I failed to register an Utterance to a Node.
